name: onco_repurpose_ai
description: A medical mobile application for cancer drug repurposing.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1 # Adding provider for state management
  sqflite: ^2.4.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # - assets/oncology_data.json
    - assets/data/Breast_Invasive_Carcinoma_TCGA/
    - assets/data/Triple_Negative_Breast_Cancer_DLDCCC/
    - assets/db/breast_cancer_clean.db
